// <auto-generated />
using System;
using AraAtti.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AraAtti.Api.Migrations
{
    [DbContext(typeof(AraAttiDbContext))]
    partial class AraAttiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AraAtti.Api.Entities.AltarContribution", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<uint>("Amount")
                        .HasColumnType("int unsigned")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)")
                        .HasColumnName("request_id");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_contributions_user");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("uk_contributions_user_request");

                    b.ToTable("altar_contributions", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.AltarState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<uint>("TargetOffering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1000u)
                        .HasColumnName("target_offering");

                    b.Property<ulong>("TotalOffered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("total_offered");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("altar_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_altar_target_positive", "`target_offering` > 0");

                            t.HasCheckConstraint("ck_altar_total_le_target", "`total_offered` <= `target_offering`");

                            t.HasCheckConstraint("ck_altar_total_nonneg", "`total_offered` >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TargetOffering = 1000u,
                            TotalOffered = 0ul,
                            UpdatedAt = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AraAtti.Api.Entities.Character", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("skin_color");

                    b.Property<byte>("SlotIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("slot_index");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_characters_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_characters_user_id");

                    b.HasIndex("UserId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("uk_characters_user_slot");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.CharacterPart", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("CharacterId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("character_id");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("prefab_name");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("uk_parts_character_slot");

                    b.ToTable("character_parts", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.PlayerInventoryItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("item_id");

                    b.Property<uint>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("uk_inventory_user_item");

                    b.ToTable("player_inventories", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.RewardClaim", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("claimed_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("game_id");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("match_key");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClaimedAt")
                        .HasDatabaseName("idx_claims_user_time");

                    b.HasIndex("UserId", "MatchKey")
                        .IsUnique()
                        .HasDatabaseName("uk_claims_user_match");

                    b.ToTable("reward_claims", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("varchar(190)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.AltarContribution", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contributions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.Character", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.CharacterPart", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.Character", "Character")
                        .WithMany("Parts")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parts_character");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.PlayerInventoryItem", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.RewardClaim", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claims_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.Character", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
