// <auto-generated />
using System;
using AraAtti.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AraAtti.Api.Migrations
{
    [DbContext(typeof(AraAttiDbContext))]
    partial class AraAttiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AraAtti.Api.Entities.Character", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("skin_color");

                    b.Property<byte>("SlotIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("slot_index");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_characters_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_characters_user_id");

                    b.HasIndex("UserId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("uk_characters_user_slot");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.CharacterPart", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("CharacterId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("character_id");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("prefab_name");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("uk_parts_character_slot");

                    b.ToTable("character_parts", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("varchar(190)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AraAtti.Api.Entities.Character", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.CharacterPart", b =>
                {
                    b.HasOne("AraAtti.Api.Entities.Character", "Character")
                        .WithMany("Parts")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parts_character");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.Character", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AraAtti.Api.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
